project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
# from django.contrib import admin
# from django.urls import path , include
# from . import views

# app_name = 'shop'
# urlpatterns = [
#     path('', views.product_list, name='product_list'),
#     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
# ]

from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=250, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=250, db_index=True, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField() 
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    
    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render , get_object_or_404
from .models import Category, Product

# Create your views here.
def product_list (request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
    }
    return render(request, 'shop/product/list.html', context)


def product_detail (request , id ,slug ): 
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    context = {
        'product': product,
    }
    return render(request, 'shop/product/detail.html', context)

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Shop{% endblock %}</title>
    <link rel="stylesheet"  type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="header">
        <a href="{% url 'shop:product_list' %}"><h1 id="ts">My Shop</h1></a>
        <div class="cart">
            Your cart is empty.
        </div>
    </div>
    
        {% block content %}
        content
        {% endblock %}
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="product-detail">
        <img src="
            {% if product.image %}
                {{ product.image.url }}
            {% else %}
                {% static 'img/default.png' %}
            {% endif %}"
        width=300px >
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock content %}

shop/templates/shop/product/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        All products
    {% endif %}
{% endblock title %}
{% block content %}
    <div id="sidebar">
        <ul>
            <h2>categories</h2>
            <li 
                {% if not category %}
                    class="selected"
                {% endif %}
            >
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
        </ul>

        {% for cat in categories %}
            <ul>
                <li {% if category.slug == cat.slug %}
                    class="selected"
                {% endif %}>
                    <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </li>
            </ul>
        {% endfor %}
    </div>

    <div id="main">
        <h1>
         {% if category %}
                {{ category.name }}
           {% else %}
                All products
           {% endif %}
        </h1>
        {% for prod in products %}
            <div class="item">
                <a href="{{ prod.get_absolute_url }}">
                    <img src="
                    {% if prod.image %}
                        {{ prod.image.url }}
                    {% else %}
                        {% static 'img/default.png' %}
                    {% endif %}"
                width=250px>
                </a><br>
                <p class="center"><a href="{{ prod.get_absolute_url }}">{{ prod.name }}</a></p>
                <br>Price: {{ prod.price }} </p>
            </div>
        {% endfor %}
    </div>
{% endblock content %}